"""DeepSeek-V4-Flash's DSpark drafter: the tail's MTP stages, graded against the reference's own.

The oracle here is `Transformer.forward_spec` -- the same six lines v4_dspark_draft mirrors, running
inside a whole reference Transformer whose `mtp` blocks hold the identical seeded weights. So every
green below is "our drafter and DeepSeek's produced the same bytes", not "our drafter produced
something plausible".

Four headlines, each a different way a speculator can be silently wrong:

  test_decode_draft_matches_oracle      the draft block, its logits and its confidence are bit-equal
      to `forward_spec`'s, every step. An untrained-looking draft is indistinguishable from a
      correct one by eye; only the oracle can tell.

  test_stepwise_advance_equals_oracle_sequence   a ring commits a RUN of positions per round and the
      reference only ever commits one. This is the proof that n+1 stepwise calls leave the mtp cache
      and the final block exactly where the reference's own sequence would.

  test_spec_loop_emits_the_greedy_stream   the end-to-end bet: verify chunk -> accept rule -> advance
      -> next chunk, over a real Stage, must emit precisely the greedy token stream. Speculation is
      only worth anything if it is LOSSLESS, and an off-by-one in the position bookkeeping shows up
      here and nowhere else.

  test_cache_never_speculative          the design claim that the drafter needs no rollback: the
      slots the draft block's own positions would occupy stay zero.

  test_ring_drafter_advances_over_the_committed_prefix   the ring adapter's one dangerous slice. A
      round's chunk and its COMMITTED prefix are the same length on a full accept, so feeding the
      wrong one is invisible to every check the drafter can make and drafts off a continuation the
      ring discarded.

Everything runs on CPU against v4_ref_cpu's toy 8-layer V4 (2 MTP stages, block_size 3, window 16,
3 DSpark taps) -- no GPU, no network, no 158 GiB checkpoint.

Run: python3 -m pytest tests/test_v4_dspark.py -q
"""
import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

torch = pytest.importorskip("torch")
safetensors_torch = pytest.importorskip("safetensors.torch")
REFCPU = pytest.importorskip("v4_ref_cpu")
V4 = pytest.importorskip("v4_stage")
DS = pytest.importorskip("v4_dspark_draft")

SEED = 7
PROMPT = 13        # < window_size (16), so the untouched tail of the mtp window is observable
STEPS = 4
RUN = 3            # committed positions in one advance
GEN = 6            # tokens generated by the end-to-end spec loop
BATCH = 1
# A random model's greedy stream usually falls into a fixed point within a token or two, and "the
# speculated stream equals the greedy stream" is worth very little when both are the same token
# repeated. This prompt's continuation is 11 distinct tokens in 12, so the equality is a fingerprint;
# _spec_loop asserts the non-degeneracy rather than trusting the seed to stay lucky.
LOOP_SEED = 3


# ── fixtures ─────────────────────────────────────────────────────────────────────────────────────

@pytest.fixture(scope="module")
def args():
    return REFCPU.cpu_args()


@pytest.fixture
def oracle(args):
    """A FRESH reference Transformer per test -- the Compressor accumulators are stateful across
    sequences (v4_ref_cpu's module docstring), so a shared oracle would grade the second test
    against the first one's tail."""
    return REFCPU.build_oracle(args, SEED)


def _ids(n, args, seed=0):
    g = torch.Generator().manual_seed(seed)
    return torch.randint(0, args.vocab_size, (BATCH, n), generator=g)


# ── oracle -> stage + drafter weight transfer ────────────────────────────────────────────────────

def tail_from_oracle(oracle, args, *, build_args=None, temperature=0.0):
    """A full-range dspark tail Stage + a DSparkTail, both holding the oracle's OWN weights.

    Mirrors tests/test_v4_stage.py::stage_from_oracle for the stage half and adds the drafter's:
    `DSparkTail.mtp[k]` is the same `DSparkBlock` class the oracle built from the same ModelArgs, so
    a state_dict transfer is exact. ALIAS_KEYS are excluded deliberately -- `mtp[k].embed`/`.head`
    are the tail's modules registered a second time, so loading them here would write the tail's own
    embedding back over itself, and a converted checkpoint does not carry them at all.

    `build_args` builds the Stage and drafter from DIFFERENT ModelArgs than the oracle's, for the
    one test that needs a config the oracle cannot mirror (a sampling temperature). Only fields that
    are not shapes may differ, or the transfer below would not be exact."""
    args = build_args or args
    st = V4.Stage(0, args.n_layers, args, head=True, tail=True, dspark=True, device="cpu")
    for li in range(args.n_layers):
        st.layers[li].load_state_dict(oracle.layers[li].state_dict(), strict=True)
    st.embed_tokens.load_state_dict(oracle.embed.state_dict(), strict=True)
    st.norm.load_state_dict(oracle.norm.state_dict(), strict=True)
    st.lm_head.load_state_dict(oracle.head.state_dict(), strict=True)
    with torch.no_grad():
        for n in ("hc_head_fn", "hc_head_base", "hc_head_scale"):
            getattr(st, n).data.copy_(getattr(oracle, n).data)
    st._dspark = True
    dr = DS.DSparkTail(st, temperature=temperature)
    for k, blk in enumerate(dr.mtp):
        sd = {n: v for n, v in oracle.mtp[k].state_dict().items() if n not in DS.ALIAS_KEYS}
        report = blk.load_state_dict(sd, strict=False)
        assert set(report.missing_keys) == set(DS.ALIAS_KEYS) and not report.unexpected_keys
    return st, dr


def step(st, tok, pos):
    """One single-token main-model step through the stage. -> (next token [b], main_hidden [b,1,·]).

    The logits go through `full_logits=False`, which is the GEMM shape greedy decode uses and the
    one the verify path has to match position for position (see v4_dspark_draft's numerics rule)."""
    ids = tok.unsqueeze(1) if tok.dim() == 1 else tok
    h = st.forward(st.embed(ids), ids, pos)
    return st.logits_all(h, full_logits=False).argmax(dim=-1), st.tail_main_hidden()


def prefilled(oracle, args, ids):
    """Prompt through both sides, oracle and Stage+DSparkTail, with the mtp caches prefilled."""
    st, dr = tail_from_oracle(oracle, args)
    o_tok, _, o_main = oracle(ids)
    assert oracle.forward_spec(o_tok, o_main) is None, "prefill forward_spec must return None"
    h = st.forward(st.embed(ids), ids, 0)
    tok = st.logits_all(h, full_logits=False).argmax(dim=-1)
    main = st.tail_main_hidden()
    assert torch.equal(tok, o_tok) and torch.equal(main, o_main), "the stage half diverged first"
    dr.prefill(tok, main)
    return st, dr, tok


def caches(dr_or_oracle):
    return [blk.attn.kv_cache.clone() for blk in dr_or_oracle.mtp]


# ── 1. prefill ───────────────────────────────────────────────────────────────────────────────────

@pytest.mark.parametrize("prompt", [PROMPT, 33])
def test_prefill_matches_oracle(oracle, args, prompt):
    """The mtp window built from the prompt is bit-identical to the reference's.

    `forward_spec(..., 0)` is a pure cache build: the DSpark blocks run only their attention, which
    writes `main_kv` for every prompt position and returns `x` untouched. Nothing else observes it,
    so the kv_cache buffers themselves are the assertion.

    Both sides of the branch at model.py:763-768 are graded: a prompt SHORTER than window_size lands
    contiguously at `[:seqlen]`, and a longer one keeps only the last `window_size` positions, split
    and rotated so that position q sits at slot `q % window_size`. 33 against a 16-slot window is
    two full wraps plus one, which is the case where an off-by-one in the split survives a shorter
    prompt. The decode branch then writes at `start_pos % win` and must agree with that layout."""
    ids = _ids(prompt, args)
    _, dr, _ = prefilled(oracle, args, ids)
    assert dr.pos == prompt - 1, "after a P-token prefill the cache stands at P-1"
    for k, (got, want) in enumerate(zip(caches(dr), caches(oracle))):
        assert torch.equal(got, want), f"mtp stage {k} window diverged"
        assert got.abs().sum() > 0, f"mtp stage {k} window is all zeros — nothing was written"


# ── 2. the draft ─────────────────────────────────────────────────────────────────────────────────

def test_decode_draft_matches_oracle(oracle, args):
    """Every decode round: draft ids, draft logits and confidence bit-equal to the oracle's triple.

    The pairing under test is the one the module docstring spells out -- `forward_spec` takes the tap
    AT position i and the token predicted FOR position i+1, and answers with drafts for i+2 onward.
    Feed it the tap and the token from the same call and the drafts are one position out, which
    nothing but the oracle would catch."""
    ids = _ids(PROMPT, args)
    st, dr, tok = prefilled(oracle, args, ids)
    for i in range(PROMPT, PROMPT + STEPS):
        o_tok, _, o_main = oracle(tok.unsqueeze(1), i)
        o_spec = oracle.forward_spec(o_tok, o_main, i)
        tok, main = step(st, tok, i)
        assert torch.equal(tok, o_tok), f"the stage half diverged at step {i}"
        drafts, conf = dr.advance_and_draft(tok.unsqueeze(1), main, start_pos=i)
        o_out, o_logits, o_conf = o_spec
        assert torch.equal(dr.last_spec[0], o_out), f"draft ids diverged at step {i}"
        assert torch.equal(dr.last_spec[1], o_logits), f"draft logits diverged at step {i}"
        assert torch.equal(conf, o_conf), f"confidence diverged at step {i}"
        assert drafts.shape == (BATCH, args.dspark_block_size)
        assert torch.equal(drafts, o_out[:, 1:]), "the returned drafts must drop the anchor column"
        assert torch.equal(o_out[:, 0], tok), "column 0 of output_ids is the token that was fed in"
        assert dr.pos == i
    for k, (got, want) in enumerate(zip(caches(dr), caches(oracle))):
        assert torch.equal(got, want), f"mtp stage {k} cache diverged over {STEPS} steps"


def test_second_choices_is_the_runner_up_at_the_drafts_own_slot(oracle, args):
    """THE INVARIANT THE TREE GATE STANDS ON (V4_DRAFT_TOP2 / docs/V4_TREE_VERDICT.md).

    `second_choices` claims `d2[i]` is the head's second choice for the SAME position that produced
    `draft[i]`, under the same conditioning. That is only true because `forward_head` adds the Markov
    bias to `logits[:, i]` IN PLACE and then samples slot i+1 from that same row (model.py:869-871)
    — so the returned logits' top-1 IS the draft, and top-2 is the branch candidate a comb tree
    would have flown. A re-vendored head that sampled first and biased after would silently turn d2
    into plausible-looking garbage; the argmax assertion here is what fails instead."""
    ids = _ids(PROMPT, args)
    st, dr, tok = prefilled(oracle, args, ids)
    tok, main = step(st, tok, PROMPT)
    drafts, _ = dr.advance_and_draft(tok.unsqueeze(1), main, start_pos=PROMPT)
    d2 = DS.second_choices(dr)
    logits = dr.last_spec[1][0]                           # [block_size, vocab], biases already in
    assert torch.equal(logits.argmax(-1), drafts[0]), \
        "the returned logits' top-1 is not the draft — the bias-then-sample order changed under us"
    top2 = logits.topk(2, dim=-1).indices[:, 1].tolist()
    assert d2 == top2 and len(d2) == drafts.shape[1], "d2 must be the runner-up, slot for slot"
    assert all(a != b for a, b in zip(d2, drafts[0].tolist())), \
        "a runner-up equal to the draft is not a second choice"
    dr.temperature = 0.5                                  # a sampling drafter: top-1 need not be the
    assert DS.second_choices(dr) is None, "draft, so there is no runner-up to claim"


# ── 3. the run ───────────────────────────────────────────────────────────────────────────────────

def test_stepwise_advance_equals_oracle_sequence(oracle, args):
    """One advance over RUN committed positions == the reference called RUN times, in order.

    This is the shape a ring actually produces: the tail forwards a whole verify chunk, so it holds
    RUN taps at once, while `forward_spec`'s decode branch is hard `seqlen == 1` and can only take
    them one at a time. The oracle's main forwards all happen before its spec calls, exactly as they
    do on the ring (the two caches are disjoint -- `forward` touches `layers`, `forward_spec`
    touches `mtp`), which is precisely what makes the batched-then-advance order legal."""
    ids = _ids(PROMPT, args, seed=LOOP_SEED)
    st, dr, tok = prefilled(oracle, args, ids)

    # The committed run is FORCED distinct ids, not the model's own stream. A verify chunk feeds
    # drafted tokens whatever the model would have said, so forcing is exactly ring semantics — and
    # it makes the pairing-shift sensitivity platform-independent: each call pairs the tap at
    # position p+j with the token at p+j+1, a shifted pairing is INVISIBLE when the run repeats a
    # token, and a natural greedy stream's diversity is platform arithmetic (the seed that gave this
    # box distinct tokens gave CI's BLAS a repeat — same model, different bf16 rounding).
    forced = [torch.full((BATCH,), t, dtype=torch.long) for t in (7, 151, 293)[:RUN]]
    toks, mains = [tok], []
    for j in range(RUN):
        _, _, o_main = oracle(toks[-1].unsqueeze(1), PROMPT + j)
        toks.append(forced[j])
        mains.append(o_main)
    o_spec = None
    for j in range(RUN):
        o_spec = oracle.forward_spec(toks[j + 1], mains[j], PROMPT + j)

    # ours: ONE chunk through the stage (its internal loop), ONE advance over the whole run
    chunk = torch.cat([t.unsqueeze(1) for t in toks[:RUN]], dim=1)
    h = st.forward(st.embed(chunk), chunk, PROMPT)
    main = st.tail_main_hidden()
    assert torch.equal(main, torch.cat(mains, dim=1)), "the stage's chunk taps diverged"
    committed = torch.cat([t.unsqueeze(1) for t in toks[1:]], dim=1)
    drafts, conf = dr.advance_and_draft(committed, main, start_pos=PROMPT)

    assert dr.pos == PROMPT + RUN - 1
    assert torch.equal(dr.last_spec[0], o_spec[0]), "final draft block diverged"
    assert torch.equal(dr.last_spec[1], o_spec[1]), "final draft logits diverged"
    assert torch.equal(conf, o_spec[2]), "final confidence diverged"
    assert torch.equal(drafts, o_spec[0][:, 1:])
    for k, (got, want) in enumerate(zip(caches(dr), caches(oracle))):
        assert torch.equal(got, want), f"mtp stage {k} cache diverged over the run"


# ── 4. the rollback that is not needed ───────────────────────────────────────────────────────────

def test_cache_never_speculative(oracle, args):
    """Drafting writes NOTHING. The advance writes exactly one slot; the block's own K/V is dropped.

    `DSparkAttention` concatenates the draft block's kv onto the cache for the attention and throws
    it away (model.py:784) -- only `main_kv`, from a COMMITTED position, is stored. PROMPT < window
    is what makes that observable: after prefilling 13 of 16 slots and advancing one position, the
    draft block's queries sit at positions 14, 15, 16, and slots 14 and 15 must still be zero. If
    they were ever written, a rejected draft would poison the next round and this drafter would need
    the snapshot/restore machinery the main Stage has."""
    win = args.window_size
    assert PROMPT + 2 < win, "this test needs untouched window slots past the prompt"
    ids = _ids(PROMPT, args)
    st, dr, tok = prefilled(oracle, args, ids)
    before = caches(dr)
    for c in before:
        assert torch.equal(c[:, PROMPT:], torch.zeros_like(c[:, PROMPT:])), "prefill overran"

    tok, main = step(st, tok, PROMPT)
    dr.advance_and_draft(tok.unsqueeze(1), main, start_pos=PROMPT)
    for k, (c, b) in enumerate(zip(caches(dr), before)):
        assert torch.equal(c[:, :PROMPT], b[:, :PROMPT]), f"mtp {k}: the advance rewrote history"
        assert not torch.equal(c[:, PROMPT], b[:, PROMPT]), f"mtp {k}: the advance wrote nothing"
        assert torch.equal(c[:, PROMPT + 1:], torch.zeros_like(c[:, PROMPT + 1:])), \
            f"mtp {k}: the draft block landed in the cache — this drafter now needs a rollback"


# ── 5. position discipline ───────────────────────────────────────────────────────────────────────

def test_pos_discipline(oracle, args):
    """A gap, an overlap, an advance before prefill and a second prefill all refuse loudly.

    The drafter's cursor is the only thing tying a draft to a position; there is no way to notice
    from the tensors that a round was skipped, so it is asserted rather than trusted."""
    ids = _ids(PROMPT, args)
    st, dr, tok = prefilled(oracle, args, ids)
    tok, main = step(st, tok, PROMPT)
    one = tok.unsqueeze(1)

    with pytest.raises(RuntimeError, match="gap"):
        dr.advance_and_draft(one, main, start_pos=PROMPT + 2)
    with pytest.raises(RuntimeError, match="overlap"):
        dr.advance_and_draft(one, main, start_pos=PROMPT - 1)
    assert dr.pos == PROMPT - 1, "a refused advance must not move the cursor"
    with pytest.raises(RuntimeError, match="already prefilled"):
        dr.prefill(tok, main)

    fresh = DS.DSparkTail(st)
    with pytest.raises(RuntimeError, match="advance before prefill"):
        fresh.advance_and_draft(one, main, start_pos=PROMPT)

    # reset -> re-prefill is bit-identical: nothing but the kv_cache and the cursor is state
    prompt_main = st.tail_main_hidden()      # (of the last step — any [b, s, ·] does here)
    dr.reset()
    assert dr.pos is None
    assert all(torch.equal(c, torch.zeros_like(c)) for c in caches(dr)), "reset left the window dirty"
    dr.prefill(tok, prompt_main)
    first = caches(dr)
    dr.reset()
    dr.prefill(tok, prompt_main)
    for k, (a, b) in enumerate(zip(caches(dr), first)):
        assert torch.equal(a, b), f"mtp {k}: a re-prefill after reset is not reproducible"


def test_drafter_on_a_split_ring_tail(oracle, args):
    """The deployment shape: a 2-stage ring whose TAIL is a layer range, not the whole stack.

    Everything above runs the drafter off a single [0, n_layers) stage, which is convenient and is
    not what a ring looks like. Here the head owns [0, 5) and the tail owns [5, 8) -- which is the
    minimum range that can hold all three dspark targets -- and the tail is built `dspark=True`
    precisely so it carries an embedding it has no other use for: `DSparkBlock.embed` aliases it.
    The drafter must not care where the layers were split, because everything it consumes crosses
    the last boundary as `main_hidden`."""
    lo = min(args.dspark_target_layer_ids)
    head = V4.Stage(0, lo, args, head=True, tail=False, device="cpu")
    tail = V4.Stage(lo, args.n_layers, args, head=False, tail=True, dspark=True, device="cpu")
    for li in range(args.n_layers):
        st = head if li < lo else tail
        st.layers[li - st.lo].load_state_dict(oracle.layers[li].state_dict(), strict=True)
    head.embed_tokens.load_state_dict(oracle.embed.state_dict(), strict=True)
    tail.embed_tokens.load_state_dict(oracle.embed.state_dict(), strict=True)
    tail.norm.load_state_dict(oracle.norm.state_dict(), strict=True)
    tail.lm_head.load_state_dict(oracle.head.state_dict(), strict=True)
    with torch.no_grad():
        for n in ("hc_head_fn", "hc_head_base", "hc_head_scale"):
            getattr(tail, n).data.copy_(getattr(oracle, n).data)
    tail._dspark = True
    dr = DS.DSparkTail(tail)
    for k, blk in enumerate(dr.mtp):
        sd = {n: v for n, v in oracle.mtp[k].state_dict().items() if n not in DS.ALIAS_KEYS}
        assert set(blk.load_state_dict(sd, strict=False).missing_keys) == set(DS.ALIAS_KEYS)

    def ring(ids, pos):
        h = tail.forward(head.forward(head.embed(ids), ids, pos), ids, pos)
        return tail.logits_all(h, full_logits=False).argmax(dim=-1), tail.tail_main_hidden()

    ids = _ids(PROMPT, args, seed=LOOP_SEED)
    o_tok, _, o_main = oracle(ids)
    assert oracle.forward_spec(o_tok, o_main) is None
    tok, main = ring(ids, 0)
    assert torch.equal(tok, o_tok) and torch.equal(main, o_main), "the ring half diverged first"
    dr.prefill(tok, main)
    for i in range(PROMPT, PROMPT + 2):
        o_tok, _, o_main = oracle(tok.unsqueeze(1), i)
        o_spec = oracle.forward_spec(o_tok, o_main, i)
        tok, main = ring(tok.unsqueeze(1), i)
        drafts, conf = dr.advance_and_draft(tok.unsqueeze(1), main, start_pos=i)
        assert torch.equal(drafts, o_spec[0][:, 1:]), f"drafts diverged over the boundary at {i}"
        assert torch.equal(conf, o_spec[2])
    for k, (got, want) in enumerate(zip(caches(dr), caches(oracle))):
        assert torch.equal(got, want), f"mtp stage {k} diverged on a split ring"


def test_reset_isolates_sequences(oracle, args):
    """A whole job, reset, a DIFFERENT job -> byte-identical to a drafter that only ever saw the second.

    The sharper half of reset(): re-prefilling the SAME prompt would still match if reset were
    incomplete, because the second pass rewrites the same slots with the same values. So the first
    sequence is LONGER than the window (its prefill wraps and fills all 16 slots) and the second is
    shorter (it writes only the first 13), which leaves three slots that can only be right if they
    were actually cleared. This is the DSpark analogue of the trap in v4_ref_cpu's docstring, where
    the compressor's accumulators survive a prefill and poison the next sequence."""
    long_ids = _ids(args.window_size + 4, args, seed=11)
    short_ids = _ids(PROMPT, args, seed=LOOP_SEED)
    assert long_ids.shape[1] > args.window_size > short_ids.shape[1]

    st, dr, tok = prefilled(oracle, args, long_ids)
    tok, main = step(st, tok, long_ids.shape[1])
    dr.advance_and_draft(tok.unsqueeze(1), main, start_pos=long_ids.shape[1])
    dirty = caches(dr)
    dr.reset()
    st.reset()

    fresh_oracle = REFCPU.build_oracle(args, SEED)
    st2, dr2, tok2 = prefilled(fresh_oracle, args, short_ids)
    h = st.forward(st.embed(short_ids), short_ids, 0)
    tok = st.logits_all(h, full_logits=False).argmax(dim=-1)
    dr.prefill(tok, st.tail_main_hidden())
    for k, (reused, virgin, was) in enumerate(zip(caches(dr), caches(dr2), dirty)):
        assert not torch.equal(was, virgin), f"mtp {k}: the two sequences are indistinguishable"
        assert torch.equal(reused, virgin), f"mtp {k}: the first sequence survived the reset"

    p = short_ids.shape[1]
    tok, main = step(st, tok, p)
    tok2, main2 = step(st2, tok2, p)
    assert torch.equal(tok, tok2) and torch.equal(main, main2), "the stage half diverged first"
    a_ids, a_conf = dr.advance_and_draft(tok.unsqueeze(1), main, start_pos=p)
    b_ids, b_conf = dr2.advance_and_draft(tok2.unsqueeze(1), main2, start_pos=p)
    assert torch.equal(a_ids, b_ids) and torch.equal(a_conf, b_conf), \
        "a reused drafter drafts differently from a fresh one"


def test_drafter_is_greedy_even_when_the_config_asks_for_sampling(args):
    """The shipped config's missing `temperature` key must not turn the drafter into a sampler.

    `DSparkBlock` copies `args.temperature` and `forward_head` draws with it (model.py:828,871).
    V4's config.json declares no temperature, so `v4_stage.config()` inherits ModelArgs' default of
    1.0 and a drafter built from a real checkpoint would Gumbel-sample every block -- off the
    process-global RNG, against a verifier that is greedy by default, at an acceptance rate near
    chance. `cpu_args()` pins 0.0, so no other test in this file can see it.

    The observable is the RNG, not the tokens: `sample()` at temperature > 0 always draws
    (`torch.empty_like(probs).exponential_(1)`, model.py:946), so a drafter that samples ADVANCES
    the global stream and a greedy one cannot. That is exact, where "the drafts differ" would depend
    on how peaked a random model's logits happen to be."""
    ref = REFCPU.load_ref()
    assert ref.ModelArgs().temperature == 1.0, "the dataclass default is what makes this a trap"
    with open(os.path.join(REFCPU.REF_DIR, "inference", "config.json")) as f:
        import json
        assert "temperature" not in json.load(f), \
            "the shipped config now sets a temperature — re-read DSparkTail's pin before trusting it"

    sampling = REFCPU.cpu_args(temperature=1.0)
    oracle = REFCPU.build_oracle(args, SEED)
    ids = _ids(PROMPT, args, seed=LOOP_SEED)

    def draw(temperature):
        st, dr = tail_from_oracle(oracle, args, build_args=sampling, temperature=temperature)
        h = st.forward(st.embed(ids), ids, 0)
        tok = st.logits_all(h, full_logits=False).argmax(dim=-1)
        dr.prefill(tok, st.tail_main_hidden())
        tok, main = step(st, tok, PROMPT)
        torch.manual_seed(1234)                       # draft, then read the stream where it stands
        drafts, _ = dr.advance_and_draft(tok.unsqueeze(1), main, start_pos=PROMPT)
        after = torch.rand(1)
        torch.manual_seed(1234)                       # the same stream, undisturbed
        return dr, drafts, torch.equal(after, torch.rand(1))

    greedy_dr, greedy_drafts, greedy_rng_intact = draw(0.0)
    assert [b.temperature for b in greedy_dr.mtp] == [0.0] * len(greedy_dr.mtp), \
        "the drafter must pin its own temperature, not inherit args.temperature"
    assert greedy_dr.args.temperature == 1.0, "the config under test really does ask for sampling"
    assert greedy_rng_intact, "a greedy drafter must not touch the global RNG"

    _, sampled_drafts, sampled_rng_intact = draw(1.0)
    assert not sampled_rng_intact, "at temperature 1.0 the reference samples — the test is inert"
    _, greedy_again, _ = draw(0.0)
    assert torch.equal(greedy_drafts, greedy_again), "the default drafter is not deterministic"
    assert sampled_drafts.shape == greedy_drafts.shape


def test_input_guards(oracle, args):
    """The refusals a caller meets before a bad advance can produce plausible drafts.

    None of these is exotic: a batch the kv_cache was never sized for, a run longer than one round
    can commit (the shape a caller gets by advancing over the whole verify chunk twice over), and a
    draft block that would rope past the end of `freqs_cis`. The last one is the context limit, and
    at the shipped config it arrives at ~4090 rather than wherever the ring thinks it is."""
    ids = _ids(PROMPT, args)
    st, dr, tok = prefilled(oracle, args, ids)
    tok, main = step(st, tok, PROMPT)
    one = tok.unsqueeze(1)

    wide = main.repeat(args.max_batch_size + 1, 1, 1)
    with pytest.raises(RuntimeError, match="exceeds max_batch_size"):
        dr.advance_and_draft(one.repeat(args.max_batch_size + 1, 1), wide, start_pos=PROMPT)

    n = args.dspark_block_size + 2
    with pytest.raises(RuntimeError, match="one round can commit at most"):
        dr.advance_and_draft(one.repeat(1, n), main.repeat(1, n, 1), start_pos=PROMPT)

    # A 1-D run is ONE batch row's POSITIONS, not one position per row -- and it takes a run of at
    # least two to tell those apart, since [n] and [n, 1] coincide at n == 1. The taps here are a
    # repeat rather than two real positions: this is about how the ids are read, and the drafter
    # cannot tell one hidden state from another.
    at = dr.pos
    got, _ = dr.advance_and_draft([int(tok), int(tok)], main.repeat(1, 2, 1), start_pos=at + 1)
    assert got.shape == (BATCH, args.dspark_block_size)
    assert dr.pos == at + 2, "a 1-D run read as a column would be b rows of one position"

    dr._pos = args.max_seq_len - 2
    with pytest.raises(RuntimeError, match="past max_seq_len"):
        dr.advance_and_draft(one, main, start_pos=args.max_seq_len - 1)
    dr._pos = args.max_seq_len - 2 - args.dspark_block_size      # the last position that still fits
    dr.advance_and_draft(one, main, start_pos=dr._pos + 1)


# ── 6. the real load path ────────────────────────────────────────────────────────────────────────

def _write_converted(oracle, d):
    """The oracle's weights in convert.py's OUTPUT format. -> the dir.

    Same writer as tests/test_v4_stage.py, and the same one filter: convert.py:91 skips
    `mtp.*.embed.*`/`mtp.*.head.weight` because the DSpark stages ALIAS the main embedding and head,
    and safetensors refuses to write one storage under two names."""
    os.makedirs(d, exist_ok=True)
    full = oracle.state_dict()
    sd = {k: v.detach().clone().contiguous() for k, v in full.items()
          if not (k.startswith("mtp.") and ("emb" in k or k.endswith("head.weight")))}
    dropped = sorted(set(full) - set(sd))
    assert dropped == [f"mtp.{k}.{n}" for k in range(len(oracle.mtp)) for n in DS.ALIAS_KEYS], \
        f"the converted format must drop exactly the aliases, dropped {dropped}"
    safetensors_torch.save_file(sd, os.path.join(d, "model0-mp1.safetensors"))
    return d


def test_load_roundtrip(oracle, args, tmp_path):
    """Stage.load + DSparkTail.load off a converted-format file reproduce the in-process transfer.

    Everything but DeepSeek's own HF->converted step. The interesting half is the alias handling:
    the file does NOT carry `mtp.k.embed.weight`/`mtp.k.head.weight`, the drafter must notice that
    those two and ONLY those two are missing, and the weights behind them must still be right --
    they came in through `Stage.load`, one object, two names."""
    d = _write_converted(oracle, str(tmp_path / "ckpt"))
    wm = V4.weight_map(d)
    assert any(k.startswith("mtp.") for k in wm), "mtp.* must be in the file"
    for k in range(len(oracle.mtp)):
        for n in DS.ALIAS_KEYS:
            assert f"mtp.{k}.{n}" not in wm, "the aliases must not be in a converted checkpoint"

    st = V4.Stage(0, args.n_layers, args, head=True, tail=True, dspark=True, device="cpu").load(d)
    st._dspark = True
    dr = DS.DSparkTail(st).load(d)
    assert dr.alias_missing == [DS.ALIAS_KEYS] * len(dr.mtp), \
        f"exactly the aliases must be reported missing, got {dr.alias_missing}"

    ids = _ids(PROMPT, args)
    o_tok, _, o_main = oracle(ids)
    assert oracle.forward_spec(o_tok, o_main) is None
    tok = st.logits_all(st.forward(st.embed(ids), ids, 0), full_logits=False).argmax(dim=-1)
    assert torch.equal(tok, o_tok)
    dr.prefill(tok, st.tail_main_hidden())
    for k, (got, want) in enumerate(zip(caches(dr), caches(oracle))):
        assert torch.equal(got, want), f"mtp stage {k} prefill diverged after a load"

    o_tok, _, o_main = oracle(tok.unsqueeze(1), PROMPT)
    o_spec = oracle.forward_spec(o_tok, o_main, PROMPT)
    tok, main = step(st, tok, PROMPT)
    drafts, conf = dr.advance_and_draft(tok.unsqueeze(1), main, start_pos=PROMPT)
    assert torch.equal(tok, o_tok)
    assert torch.equal(drafts, o_spec[0][:, 1:]) and torch.equal(conf, o_spec[2])
    assert torch.equal(dr.last_spec[1], o_spec[1])


def test_load_refuses_a_checkpoint_without_mtp(oracle, args, tmp_path):
    """No `mtp.*` at all, and a stage short one MTP tensor, both raise rather than random-init."""
    d = str(tmp_path / "nomtp")
    os.makedirs(d, exist_ok=True)
    sd = {k: v.detach().clone().contiguous() for k, v in oracle.state_dict().items()
          if not k.startswith("mtp.")}
    safetensors_torch.save_file(sd, os.path.join(d, "model0-mp1.safetensors"))
    st = V4.Stage(0, args.n_layers, args, head=True, tail=True, dspark=True, device="cpu").load(d)
    with pytest.raises(RuntimeError, match="no tensor under 'mtp.0.'"):
        DS.DSparkTail(st).load(d)

    holed = _write_converted(oracle, str(tmp_path / "holed"))
    keep = {k: v for k, v in safetensors_torch.load_file(
        os.path.join(holed, "model0-mp1.safetensors")).items() if k != "mtp.0.attn.wq_a.weight"}
    safetensors_torch.save_file(keep, os.path.join(holed, "model0-mp1.safetensors"))
    V4._WM.pop(holed, None)
    V4._HD.pop((holed, "model0-mp1.safetensors"), None)
    with pytest.raises(RuntimeError, match="missing"):
        DS.DSparkTail(st).load(holed)


# ── 7. the accept rule ───────────────────────────────────────────────────────────────────────────

def test_plan_verify_round():
    """Longest matching prefix + the correction, and the bonus token on a full accept."""
    assert DS.plan_verify_round([1, 2, 3], [1, 2, 3, 9]) == (3, [1, 2, 3, 9])   # full + bonus
    assert DS.plan_verify_round([1, 2, 3], [1, 7, 3, 9]) == (1, [1, 7])         # partial
    assert DS.plan_verify_round([1, 2, 3], [5, 2, 3, 9]) == (0, [5])            # nothing
    assert DS.plan_verify_round([], [5]) == (0, [5])                            # round 0 / greedy
    for drafts, replies in (([1, 2, 3], [1, 2, 3, 9]), ([1, 2, 3], [1, 7, 3, 9]),
                            ([1, 2, 3], [5, 2, 3, 9]), ([], [5])):
        n, committed = DS.plan_verify_round(drafts, replies)
        assert len(committed) == n + 1, "one committed token per accepted draft, plus the correction"
        assert committed[:n] == drafts[:n] == replies[:n], "an accepted token IS the model's own"
        assert committed[-1] == replies[n], "the last committed token always comes from the model"
    with pytest.raises(RuntimeError, match="need 3 replies"):
        DS.plan_verify_round([1, 2], [1, 2])


# ── 8. the end-to-end bet ────────────────────────────────────────────────────────────────────────

def _greedy_stream(args, ids, n):
    """The truth: `n` greedy tokens from a fresh oracle, positions PROMPT..PROMPT+n-1."""
    ref = REFCPU.build_oracle(args, SEED)
    tok, _, _ = ref(ids)
    out = [int(tok)]
    for i in range(ids.shape[1], ids.shape[1] + n - 1):
        tok, _, _ = ref(tok.unsqueeze(1), i)
        out.append(int(tok))
    return out


def _rich_ids(args, n):
    """A prompt whose greedy stream is non-constant ON THIS PLATFORM, richest of a fixed seed list.

    The stream's token VALUES are platform arithmetic: the seed that gives one box 4+ distinct
    tokens gave CI's BLAS 3 (bf16 rounds differently at toy scale), and a CONSTANT stream would
    make a stream-equality assertion vacuous — any misalignment emits the same constant. The parity
    bar itself is within-platform, so any non-constant stream carries it; searching a fixed list
    keeps the choice deterministic per box and loud when no candidate qualifies."""
    best = None
    for seed in (LOOP_SEED, 5, 11, 29, 47):
        ids = _ids(PROMPT, args, seed=seed)
        want = _greedy_stream(args, ids, n)
        k = len(set(want[:GEN]))
        if best is None or k > best[0]:
            best = (k, ids, want)
        if k >= 4:
            break
    assert best[0] >= 2, "every candidate seed yields a CONSTANT greedy stream on this platform"
    return best[1], best[2]


def _rewind(st, ids, committed):
    """Put the stage back to 'has seen the prompt + `committed`'. Step 5's rollback, the slow way.

    `Stage._seek` refuses a rewind today (that is step 5, where `_snapshot`/`_restore` hook in), so
    the test replays from scratch: reset, re-prefill, then feed the committed tokens ONE AT A TIME.
    Deliberately the dumbest possible rewind -- a test that leaned on the rollback seam would be
    grading step 5's design instead of this file's protocol."""
    st.reset()
    st.forward(st.embed(ids), ids, 0)
    for j, t in enumerate(committed):
        one = torch.tensor([[t]], dtype=torch.long)
        st.forward(st.embed(one), one, ids.shape[1] + j)


def _spec_loop(oracle, args, ids, propose):
    """The ring's round, in one process: verify chunk -> accept -> advance -> next chunk.

    `propose(drafts)` picks what actually goes on the wire, so the same loop runs with the real
    drafter and with a perfect one. The verify logits are taken PER POSITION with full_logits=False,
    which is v4_dspark_draft's numerics rule: the same GEMM shape greedy decode uses, so a
    speculated token is bit-identical to the greedy one instead of a 4e-7 argmax coin flip."""
    st, dr, tok = prefilled(oracle, args, ids)
    out = [int(tok)]                          # token at position PROMPT — not fed anywhere yet
    drafts, drafted, rewound = [], 0, 0
    while len(out) < GEN:
        p = ids.shape[1] + len(out) - 1        # absolute position of the chunk's first token
        chunk = torch.tensor([[out[-1]] + list(drafts)], dtype=torch.long)
        drafted += bool(drafts)
        h = st.forward(st.embed(chunk), chunk, p)
        replies = [int(st.logits_all(h[:, j:j + 1], full_logits=False).argmax(-1))
                   for j in range(chunk.shape[1])]
        n, committed = DS.plan_verify_round(drafts, replies)
        taps = st.tail_main_hidden()[:, :n + 1]
        out.extend(committed)
        if len(out) >= GEN:
            break
        got, _ = dr.advance_and_draft(torch.tensor([committed], dtype=torch.long), taps, start_pos=p)
        assert dr.pos == p + n
        drafts = propose(got[0].tolist())
        if n + 1 != chunk.shape[1]:            # a rejected tail was fed and must be un-fed
            _rewind(st, ids, out[:-1])
            rewound += 1
    return out, drafted, rewound


def test_spec_loop_emits_the_greedy_stream(oracle, args):
    """The real drafter, driving real rounds: the emitted stream IS the greedy stream.

    The headline. Lossless is the whole claim of speculative decoding, and every position mistake in
    the protocol -- a tap paired with the wrong token, an advance over the rejected tail, a draft
    block read one column off -- changes this stream and nothing else visible."""
    ids, want = _rich_ids(args, GEN + args.dspark_block_size)
    got, drafted, rewound = _spec_loop(oracle, args, ids, lambda d: d)
    assert got == want[:len(got)], "the speculated stream is not the greedy stream"
    assert len(got) >= GEN
    assert drafted >= 2, "every round after the first must carry a real draft block"
    assert rewound >= 1, "no round was rejected — the rewind path was never exercised"


# ── 9. the ring adapter ──────────────────────────────────────────────────────────────────────────
# RingDrafter is the tail-side protocol: chunk in, (accept length, next block) out. Everything it can
# get wrong is a SLICE — which taps, which tokens, which position — and a wrong slice still produces
# well-shaped drafts. So it is driven against a recorder that captures exactly what it handed the
# drafter, with taps whose VALUES identify their position; the real-weights version of this same
# protocol is the dspark ring in tests/test_v4_pipe.py.

class _RecordingTail:
    """A DSparkTail's contract, recording what it was handed. Nothing computes."""

    def __init__(self, block_size=3, max_seq_len=256, block=(71, 72, 73)):
        self.block_size = block_size
        self.args = type("A", (), {"max_seq_len": max_seq_len})()
        self.block = list(block)
        self.calls = []

    def reset(self):
        self.calls.append(("reset",))

    def prefill(self, pred_ids, main_hidden):
        self.calls.append(("prefill", [int(t) for t in pred_ids], _rows(main_hidden)))

    def advance_and_draft(self, ids_seq, main_hidden_seq, start_pos):
        self.calls.append(("advance", [int(t) for t in torch.as_tensor(ids_seq).reshape(-1)],
                           _rows(main_hidden_seq), start_pos))
        return (torch.tensor([self.block], dtype=torch.long),
                torch.tensor([[0.5] * len(self.block)]))


class _TapStage:
    """A tail Stage's one method the drafter uses, with taps that SAY which position they are: row j
    is the constant j, so a slice taken from the wrong end is visible instead of merely mis-shaped."""

    def __init__(self, s, dim=6):
        self.taps = torch.arange(s, dtype=torch.float32).view(1, s, 1).repeat(1, 1, dim)

    def tail_main_hidden(self):
        return self.taps


def _rows(t):
    """The positions a [1, s, d] tap tensor covers, read back off _TapStage's marking."""
    return [int(r[0]) for r in torch.as_tensor(t)[0]]


def _chunk(ids, start_pos, tokens=None, token=None):
    msg = {"ids": [list(ids)], "start_pos": start_pos}
    out = {"token": token if token is not None else (tokens[-1] if tokens else 0)}
    if tokens is not None:
        out["tokens"] = list(tokens)
    return msg, out


def test_ring_drafter_prefill_round_drafts_nothing():
    """The ring's prefill primes the mtp window over the whole prompt and returns NO draft, so round
    1 is the bare `[cur]` chunk. The token it primes with is the one the model predicted for position
    P — the reply's own `token` — and the taps are all P of the prompt's."""
    tail = _RecordingTail()
    dr = DS.RingDrafter(tail)
    msg, out = _chunk([5, 6, 7, 8], 0, token=99)
    assert dr.on_chunk(msg, _TapStage(4), out) == {}
    assert tail.calls == [("reset",), ("prefill", [99], [0, 1, 2, 3])]


def test_ring_drafter_bare_round_advances_exactly_one():
    """Round 1 carries no drafts: the accept rule's degenerate case commits one token, so the drafter
    advances over one position — the chunk's own — and drafts from there."""
    tail = _RecordingTail()
    dr = DS.RingDrafter(tail)
    msg, out = _chunk([5, 6, 7], 0, token=42)              # the ring's prefill, as above
    dr.on_chunk(msg, _TapStage(3), out)
    tail.calls.clear()

    msg, out = _chunk([42], 7, tokens=[63])
    rep = dr.on_chunk(msg, _TapStage(1), out)
    assert rep == {"draft": [71, 72, 73], "n": 0, "conf": [0.5, 0.5, 0.5]}
    assert tail.calls == [("advance", [63], [0], 7)], "one committed position, its own tap, at pos 7"


@pytest.mark.parametrize("tokens,n,committed,taps", [
    ([7, 8, 55, 0], 2, [7, 8, 55], [0, 1, 2]),        # partial: drafts 7,8 accepted, 9 rejected
    ([90, 0, 0, 0], 0, [90], [0]),                    # nothing accepted: one correction, one tap
    ([7, 8, 9, 11], 3, [7, 8, 9, 11], [0, 1, 2, 3]),  # full accept + the bonus token
])
def test_ring_drafter_advances_over_the_committed_prefix(tokens, n, committed, taps):
    """THE slice that matters: the drafter is advanced over the ACCEPTED PREFIX of the round, never
    over the whole chunk.

    Feeding the chunk instead passes every check the drafter itself can make — a full accept commits
    g+1 positions, so length alone cannot tell them apart — and drafts off a continuation the ring
    threw away. Here the committed tokens and the taps' own position markers are both asserted, for
    every accept length a round can produce."""
    tail = _RecordingTail()
    dr = DS.RingDrafter(tail)
    msg, out = _chunk([1, 2], 0, token=42)
    dr.on_chunk(msg, _TapStage(2), out)
    tail.calls.clear()

    msg, out = _chunk([42, 7, 8, 9], 7, tokens=tokens)
    rep = dr.on_chunk(msg, _TapStage(4), out)
    assert rep["n"] == n and rep["draft"] == [71, 72, 73]
    assert tail.calls == [("advance", committed, taps, 7)]


def test_ring_drafter_refuses_what_it_cannot_answer():
    """Two refusals, both about a reply the protocol cannot express: a batch (the tail answers for row
    0 alone) and a dspark job whose reset forgot `spec` (no per-position tokens, hence no accept)."""
    dr = DS.RingDrafter(_RecordingTail())
    st = _TapStage(2)
    with pytest.raises(RuntimeError, match="single-sequence"):
        dr.on_chunk({"ids": [[1, 2], [3, 4]], "start_pos": 3}, st, {"token": 1, "tokens": [1, 2]})
    with pytest.raises(RuntimeError, match="must arm `spec`"):
        dr.on_chunk({"ids": [[1, 2]], "start_pos": 3}, st, {"token": 1})


def test_ring_drafter_degrades_to_greedy_at_the_context_limit():
    """The context cliff. `advance_and_draft` REFUSES to rope a block past max_seq_len — correct for
    the drafter, fatal for the ring, because an exception in the tail's serve loop takes the whole
    ring down with it and the coordinator (which only ever reads the tail) sees a stall. So the last
    rounds of a max-length generation stop drafting and keep answering, and once stopped they stay
    stopped: the drafter's cursor no longer tracks the stream."""
    tail = _RecordingTail(max_seq_len=20)
    dr = DS.RingDrafter(tail)
    msg, out = _chunk([1, 2], 0, token=42)
    dr.on_chunk(msg, _TapStage(2), out)
    tail.calls.clear()

    at = tail.args.max_seq_len - tail.block_size            # a block from here would rope past the end
    msg, out = _chunk([42, 7], at, tokens=[7, 8])
    rep = dr.on_chunk(msg, _TapStage(2), out)
    assert rep == {"draft": [], "n": 1}, "the accept still has to be reported — the ring commits it"
    assert tail.calls == [], "nothing may reach the drafter once it would raise"
    msg, out = _chunk([9], 1, tokens=[10])                 # and it stays stopped for the job
    rep = dr.on_chunk(msg, _TapStage(1), out)
    assert rep == {"draft": [], "n": 0} and tail.calls == []


# ── 7b. PIPELINED mode: the same accept rule, one streamed s=1 frame at a time ────────────────────


def _pframe(ids, start_pos, tokens=None, token=None):
    """One streamed frame + the reply the tail has already built for it (the model's greedy token at
    this frame's position), in RingDrafter.on_chunk's (msg, st, out) shape."""
    msg, out = _chunk(ids, start_pos, tokens=tokens, token=token)
    return msg, _TapStage(len(ids)), out


def _pipelined_drafter(prompt_len=4, first=99, **kw):
    """A pipelined RingDrafter with the ring's prefill already behind it. -> (drafter, tail)."""
    tail = _RecordingTail(**kw)
    dr = DS.RingDrafter(tail)
    dr.pipelined = True
    dr.on_chunk(*_pframe(list(range(prompt_len)), 0, token=first))
    tail.calls.clear()
    return dr, tail


def test_pipelined_prefill_seeds_the_frontier_and_drafts_nothing():
    """Identical to the serial prefill — the whole prompt's taps, no block — plus the one thing the
    streamed path needs from it: the frontier. The last prompt position is committed by construction
    and the reply's own token is the model's at the one after it, which is exactly what the first
    streamed frame will carry."""
    tail = _RecordingTail()
    dr = DS.RingDrafter(tail)
    dr.pipelined = True
    assert dr.on_chunk(*_pframe([5, 6, 7, 8], 0, token=99)) == {"acc": True}
    assert tail.calls == [("reset",), ("prefill", [99], [0, 1, 2, 3])]
    assert (dr._cfront, dr._mfront) == (3, 99)


def test_pipelined_committed_frame_advances_exactly_one_position_and_drafts():
    """A frame carrying the model's own token at the frontier is COMMITTED: the drafter advances over
    that one position, pairing this frame's tap with this frame's greedy reply, and the block it
    returns is the speculation the coordinator streams behind the token it is about to commit."""
    dr, tail = _pipelined_drafter(prompt_len=4, first=99)
    rep = dr.on_chunk(*_pframe([99], 4, tokens=[63]))
    assert rep == {"acc": True, "draft": [71, 72, 73], "conf": [0.5, 0.5, 0.5]}
    assert tail.calls == [("advance", [63], [0], 4)], "one position, its own tap, at the frontier"


def test_pipelined_rejects_a_speculative_frame_and_everything_streamed_behind_it():
    """THE INCREMENTAL ACCEPT RULE, including the part that is easy to get wrong.

    A frame whose token is not the model's at that position is speculative-and-wrong: it must not move
    the frontier and must not touch the drafter. Neither may ANY frame streamed behind it — and the
    frame behind it here carries exactly the greedy token the REJECTED frame produced, which is what a
    naive "does this match the last reply" rule would accept, drafting off a history the ring threw
    away. The frontier test (`q == cfront + 1`) is what refuses it. The coordinator's correction lands
    back AT the frontier with the model's own token, and re-opens."""
    dr, tail = _pipelined_drafter(prompt_len=4, first=99)
    dr.on_chunk(*_pframe([99], 4, tokens=[63]))                # committed: frontier 4, model says 63
    tail.calls.clear()
    assert dr.on_chunk(*_pframe([500], 5, tokens=[64])) == {"acc": False}, "a wrong draft"
    assert dr.on_chunk(*_pframe([64], 6, tokens=[65])) == {"acc": False}, "poisoned: behind a reject"
    assert tail.calls == [], "a speculative frame must never advance the drafter"
    rep = dr.on_chunk(*_pframe([63], 5, tokens=[77]))          # the correction, at the frontier
    assert rep["acc"] is True and tail.calls == [("advance", [77], [0], 5)]


def test_pipelined_refuses_a_multi_token_frame():
    """The whole point of the lever is that no stage replays a block position by position, so a
    pipelined frame is s=1 by construction and anything else is a coordinator bug."""
    dr, _tail = _pipelined_drafter()
    with pytest.raises(RuntimeError, match="streams s=1 frames"):
        dr.on_chunk(*_pframe([99, 7], 4, tokens=[63, 64]))


def test_pipelined_degrades_to_greedy_at_the_context_limit():
    """The context cliff, pipelined: stop drafting before a block would rope past max_seq_len, but
    keep judging frames — the frontier has to keep moving or the coordinator's next frame is refused.
    The run degrades to one frame in flight, which is plain greedy decode."""
    dr, tail = _pipelined_drafter(prompt_len=4, first=99, max_seq_len=20)
    at = tail.args.max_seq_len - tail.block_size               # a block from here ropes past the end
    dr._cfront, dr._mfront = at - 1, 99
    assert dr.on_chunk(*_pframe([99], at, tokens=[7])) == {"acc": True, "draft": []}
    assert tail.calls == [], "nothing may reach the drafter once it would raise"
    assert (dr._cfront, dr._mfront) == (at, 7), "the frontier still has to advance"
    assert dr.on_chunk(*_pframe([7], at + 1, tokens=[8])) == {"acc": True, "draft": []}


def test_pipelined_stepwise_advance_equals_one_multiposition_advance(oracle, args):
    """The decomposition the pipelined drafter rests on: advancing ONE position per streamed frame is
    bit-identical to the serial round's single call over the whole committed run.

    It has to be, and not merely "close": if the two cadences produced different mtp state, the two
    coordinators would propose different blocks off the same history, and every acceptance measurement
    taken on one path would say nothing about the other. `advance_and_draft` loops per position
    internally and keeps the last block, so this is really the assertion that the loop has no state
    outside the drafter — proven on two independent drafters prefilled from the same tensors."""
    ids = _ids(PROMPT, args, seed=LOOP_SEED)
    st, serial, tok = prefilled(oracle, args, ids)
    main0 = st.tail_main_hidden()                              # the prompt's taps, still the last forward
    _st_b, streamed = tail_from_oracle(oracle, args)
    streamed.prefill(tok, main0)

    forced = [torch.full((BATCH,), t, dtype=torch.long) for t in (7, 151, 293)[:RUN]]
    toks = [tok] + forced
    chunk = torch.cat([t.unsqueeze(1) for t in toks[:RUN]], dim=1)
    h = st.forward(st.embed(chunk), chunk, PROMPT)
    main = st.tail_main_hidden()
    committed = torch.cat([t.unsqueeze(1) for t in toks[1:]], dim=1)

    d_serial, c_serial = serial.advance_and_draft(committed, main, start_pos=PROMPT)
    for j in range(RUN):                                       # the pipelined cadence: one at a time
        d_stream, c_stream = streamed.advance_and_draft(committed[:, j:j + 1], main[:, j:j + 1],
                                                        start_pos=PROMPT + j)
    assert serial.pos == streamed.pos == PROMPT + RUN - 1
    assert torch.equal(d_serial, d_stream), "the block differs between the two cadences"
    assert torch.equal(c_serial, c_stream), "the confidence differs between the two cadences"
    for k, (a, b) in enumerate(zip(caches(serial), caches(streamed))):
        assert torch.equal(a, b), f"mtp stage {k} cache differs between the two cadences"


def test_ring_drafter_over_the_real_drafter(oracle, args):
    """The same adapter, over a real Stage + DSparkTail: one drafted round, graded on the oracle.

    The recorder above proves the slices; this proves they are the slices the REFERENCE wants. The
    ring's own reply is assembled by hand (a chunk of one, the tail's greedy token) so the assertion
    is about RingDrafter and not about v4_pipe's serve loop."""
    ids = _ids(PROMPT, args, seed=LOOP_SEED)
    st, dr_tail, tok = prefilled(oracle, args, ids)
    o_tok, _, o_main = oracle(tok.unsqueeze(1), PROMPT)
    o_spec = oracle.forward_spec(o_tok, o_main, PROMPT)

    ring = DS.RingDrafter(dr_tail)
    h = st.forward(st.embed(tok.unsqueeze(1)), tok.unsqueeze(1), PROMPT)
    reply = int(st.logits_all(h, full_logits=False).argmax(-1))
    rep = ring.on_chunk({"ids": [[int(tok)]], "start_pos": PROMPT}, st,
                        {"token": reply, "tokens": [reply]})
    assert rep["n"] == 0, "a bare round accepts nothing and commits the model's own token"
    assert rep["draft"] == o_spec[0][0, 1:].tolist(), "the block is not the reference's"
    assert dr_tail.pos == PROMPT


def test_spec_loop_with_a_perfect_drafter(oracle, args):
    """Same loop, drafts replaced by the true continuation: full accepts, bonus token, no rewind.

    A random-weight drafter proposes almost nothing acceptable, so the real loop above only ever
    exercises n = 0. This one forces n = block_size every round -- the multi-position advance, the
    full-accept bonus, and the case where the chunk the stage consumed happens to be exactly what
    was committed. Both loops must emit the same greedy stream."""
    ids, want = _rich_ids(args, GEN + args.dspark_block_size + 1)
    g = args.dspark_block_size

    def perfect(_):
        return want[len(perfect.out) : len(perfect.out) + g]
    perfect.out = []

    st, dr, tok = prefilled(oracle, args, ids)
    out, accepted = [int(tok)], []
    drafts = []
    while len(out) < GEN:
        p = ids.shape[1] + len(out) - 1
        chunk = torch.tensor([[out[-1]] + list(drafts)], dtype=torch.long)
        h = st.forward(st.embed(chunk), chunk, p)
        replies = [int(st.logits_all(h[:, j:j + 1], full_logits=False).argmax(-1))
                   for j in range(chunk.shape[1])]
        n, committed = DS.plan_verify_round(drafts, replies)
        assert n == len(drafts), f"a perfect draft must be fully accepted, got {n}/{len(drafts)}"
        assert len(committed) == n + 1, "a full accept still commits the bonus token"
        taps = st.tail_main_hidden()[:, :n + 1]
        out.extend(committed)
        accepted.append(n)
        dr.advance_and_draft(torch.tensor([committed], dtype=torch.long), taps, start_pos=p)
        assert dr.pos == p + n and st._pos == p + n + 1, "a full accept needs no stage rewind"
        perfect.out = out
        drafts = perfect(None)
    assert out == want[:len(out)]
    assert max(accepted) == g, "the perfect drafter never reached a full block"


# ── 9. the inference-time block width (V4_DSPARK_BLOCK) ──────────────────────────────────────────

def test_width_override_is_off_by_default_and_bounded(oracle, args, monkeypatch):
    """Default 0 = the trained width, exactly — and the guard refuses a width the serial reset's
    declared overshoot (`v4_pipe._SPEC_POS_MARGIN`) could not cover, at build rather than as a
    horizon violation mid-job."""
    assert DS.V4_DSPARK_BLOCK == 0, "the width override must ship OFF"
    _, dr = tail_from_oracle(oracle, args)
    assert dr.block_size == args.dspark_block_size
    for bad in (33, -1):
        monkeypatch.setattr(DS, "V4_DSPARK_BLOCK", bad)
        with pytest.raises(ValueError, match="V4_DSPARK_BLOCK"):
            tail_from_oracle(oracle, args)


def test_width_override_drafts_wider_bit_equal_to_a_widened_reference(oracle, args, monkeypatch):
    """RENT-NOT-REWRITE at the new width: the override only CONFIGURES the vendored blocks, so a
    reference widened the same way must produce the same bytes — drafts, logits, confidence — for
    every step, with the mtp caches identical after. `block_size` is instance state on DSparkBlock
    and no weight tensor is dimensioned by it; this is the proof that stays true.

    The oracle's own mtp blocks are widened directly (the same one-attribute change the lever
    makes), so both sides run DeepSeek's forward at width 7 and the comparison is exact."""
    WIDE = 7
    monkeypatch.setattr(DS, "V4_DSPARK_BLOCK", WIDE)
    for blk in oracle.mtp:
        blk.block_size = WIDE
    ids = _ids(PROMPT, args)
    st, dr, tok = prefilled(oracle, args, ids)
    assert dr.block_size == WIDE and all(b.block_size == WIDE for b in dr.mtp)
    for i in range(PROMPT, PROMPT + STEPS):
        o_tok, _, o_main = oracle(tok.unsqueeze(1), i)
        o_spec = oracle.forward_spec(o_tok, o_main, i)
        tok, main = step(st, tok, i)
        assert torch.equal(tok, o_tok), f"the stage half diverged at step {i}"
        drafts, conf = dr.advance_and_draft(tok.unsqueeze(1), main, start_pos=i)
        o_out, o_logits, o_conf = o_spec
        assert drafts.shape == (BATCH, WIDE), "the widened drafter must return WIDE drafts"
        assert torch.equal(dr.last_spec[0], o_out), f"widened draft ids diverged at step {i}"
        assert torch.equal(dr.last_spec[1], o_logits), f"widened draft logits diverged at step {i}"
        assert torch.equal(conf, o_conf), f"widened confidence diverged at step {i}"
        assert dr.pos == i
    for k, (got, want) in enumerate(zip(caches(dr), caches(oracle))):
        assert torch.equal(got, want), f"mtp stage {k} cache diverged at width {WIDE}"


def test_widening_perturbs_the_trained_slots_and_that_is_the_documented_price(oracle, args,
                                                                              monkeypatch):
    """THE HONEST PRICE, pinned as a fact rather than left as prose: `get_dspark_topk_idxs` gives
    every block query the same index set, so the block attends to itself BIDIRECTIONALLY and the
    extra noise slots feed back into the trained slots' logits. A widened block is therefore NOT
    "the trained block plus free extras" — the per-depth acceptance of slots 1..B is a new
    measurement under the lever, which is exactly what `accept_by_depth` on the first widened ring
    run must be read for. If this assertion ever starts failing, the attention became causal and
    the lever's risk paragraph should be rewritten, not this test deleted."""
    WIDE = 7
    ids = _ids(PROMPT, args)
    st, dr, tok0 = prefilled(oracle, args, ids)
    o_tok, _, o_main = oracle(tok0.unsqueeze(1), PROMPT)
    tok, main = step(st, tok0, PROMPT)
    narrow, _ = dr.advance_and_draft(tok.unsqueeze(1), main, start_pos=PROMPT)
    narrow_logits = dr.last_spec[1][:, :args.dspark_block_size]

    monkeypatch.setattr(DS, "V4_DSPARK_BLOCK", WIDE)
    oracle2 = REFCPU.build_oracle(args, SEED)
    st2, dr2, tok0w = prefilled(oracle2, args, ids)
    assert torch.equal(tok0w, tok0), "the main model must not see the drafter's width"
    tokw, mainw = step(st2, tok0w, PROMPT)
    assert torch.equal(tokw, tok), "the main model's stream is width-independent by construction"
    wide, _ = dr2.advance_and_draft(tokw.unsqueeze(1), mainw, start_pos=PROMPT)
    wide_logits = dr2.last_spec[1][:, :args.dspark_block_size]
    assert wide.shape[1] == WIDE and narrow.shape[1] == args.dspark_block_size
    assert not torch.equal(wide_logits, narrow_logits), (
        "widening left the trained slots' logits bit-identical — the block attention has become "
        "causal within the block, and V4_DSPARK_BLOCK's documented risk paragraph is now stale")
